# Generated by Django 5.1.3 on 2024-11-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcort', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
