# Generated by Django 5.1.3 on 2024-11-14 09:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcort', '0006_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name='Stol raqami')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Komentariya')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 14, 8, 59, 833315), null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Komentariyalar',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name='Stol raqami')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 14, 8, 59, 833315), null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Food Comment',
                'verbose_name_plural': 'Taom uchun baholar',
                'db_table': 'food_comment',
            },
        ),
        migrations.CreateModel(
            name='WaiterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name='Stol raqami')),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 14, 8, 59, 833315), null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Waiter Comment',
                'verbose_name_plural': 'Ofitsiant uchun baholar',
                'db_table': 'waiter_comment',
            },
        ),
    ]
