# Generated by Django 5.1.3 on 2024-11-14 10:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcort', '0007_comments_foodcomment_waitercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcort.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcort.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='waitercomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcort.user', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 15, 32, 39, 558317), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='foodcomment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 15, 32, 39, 557318), null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='waitercomment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 14, 15, 32, 39, 557318), null=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
