# Generated by Django 5.1.3 on 2024-11-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcort', '0008_comments_user_foodcomment_user_waitercomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='foodcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='waitercomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
