# Generated by Django 5.1.3 on 2024-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcort', '0009_alter_comments_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='table_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Stol raqami'),
        ),
        migrations.AlterField(
            model_name='foodcomment',
            name='table_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Stol raqami'),
        ),
        migrations.AlterField(
            model_name='waitercomment',
            name='table_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Stol raqami'),
        ),
    ]
